[package]
name = "eka_ci_server"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Ringer <jonringer117@gmail.com>"]
description = "Continuous Integration server for Nix"
repository = "https://github.com/ekala-project/eka-ci"

[dependencies]
chrono = "0.4.38"
clap = {workspace = true}
env_logger = {workspace = true}
jsonwebtoken = "9.3.0"
log = "0.4.22"
octocrab = "0.41.2"
tokio = { version = "1.41.0", features = ["full"] }
warp = "0.3.7"
xdg = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
shared = { path = "../shared" }
